#####################
# Defines the Schemas for routes
# https://json-schema.org/learn/miscellaneous-examples.html
#####################
labels:
  ok:  "resp.status == 200"
  err:  "resp.status != 200"

verify:
  in: true
  out: true

routes:
  /calculateDistance:
    post:
      in: distanceApiInput.json
      ok: distanceApiRetVal.json
      err: distanceApiRetVal.json
  /user/poll:
    post:
      in: registerPersonInput.json
      ok: registerPersonRetVal.json
      err: registerPersonRetVal.json
  /locations:
    post:
      in: locationsInput.json
      ok: locationsRetVal.json
      err: locationsRetVal.json

